// generated by goplater -type=WeekDay; DO NOT EDIT
package main

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
)

func init() {
	// stub usage of json for situation when
	// (Un)MarshalJSON methods will be omitted
	_ = json.Delim('s')

	// stub usage of sql/driver for situation when
	// Scan/Value methods will be omitted
	_ = driver.Bool
	_ = sql.LevelDefault
}

var ErrWeekDayInvalid = errors.New("WeekDay is invalid")

func init() {
	var v WeekDay
	if _, ok := interface{}(v).(fmt.Stringer); ok {
		defWeekDayNameToValue = map[string]WeekDay{
			interface{}(Monday).(fmt.Stringer).String():    Monday,
			interface{}(Tuesday).(fmt.Stringer).String():   Tuesday,
			interface{}(Wednesday).(fmt.Stringer).String(): Wednesday,
			interface{}(Thursday).(fmt.Stringer).String():  Thursday,
			interface{}(Friday).(fmt.Stringer).String():    Friday,
			interface{}(Saturday).(fmt.Stringer).String():  Saturday,
			interface{}(Sunday).(fmt.Stringer).String():    Sunday,
		}
	}
}

var defWeekDayNameToValue = map[string]WeekDay{
	"Monday":    Monday,
	"Tuesday":   Tuesday,
	"Wednesday": Wednesday,
	"Thursday":  Thursday,
	"Friday":    Friday,
	"Saturday":  Saturday,
	"Sunday":    Sunday,
}

var defWeekDayValueToName = map[WeekDay]string{
	Monday:    "Monday",
	Tuesday:   "Tuesday",
	Wednesday: "Wednesday",
	Thursday:  "Thursday",
	Friday:    "Friday",
	Saturday:  "Saturday",
	Sunday:    "Sunday",
}

// Validate verifies that value is predefined for WeekDay.
func (r WeekDay) Validate() error {
	_, ok := defWeekDayValueToName[r]
	if !ok {
		return ErrWeekDayInvalid
	}
	return nil
}

// MarshalJSON is generated so WeekDay satisfies json.Marshaler.
func (r WeekDay) MarshalJSON() ([]byte, error) {
	if s, ok := interface{}(r).(fmt.Stringer); ok {
		return json.Marshal(s.String())
	}
	s, ok := defWeekDayValueToName[r]
	if !ok {
		return nil, fmt.Errorf("WeekDay(%d) is invalid value", r)
	}
	return json.Marshal(s)
}

// UnmarshalJSON is generated so WeekDay satisfies json.Unmarshaler.
func (r *WeekDay) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("WeekDay: should be a string, got %s", string(data))
	}
	v, ok := defWeekDayNameToValue[s]
	if !ok {
		return fmt.Errorf("WeekDay(%q) is invalid value", s)
	}
	*r = v
	return nil
}

// Value is generated so WeekDay satisfies db row driver.Valuer.
func (r WeekDay) Value() (driver.Value, error) {
	j, err := json.Marshal(r)
	return j, err
}

// Value is generated so WeekDay satisfies db row driver.Scanner.
func (r *WeekDay) Scan(src interface{}) error {
	switch src.(type) {
	case string:
		val, ok := defWeekDayNameToValue[src.(string)]
		if !ok {
			return errors.New("WeekDay: can't unmarshal column data")
		}
		*r = val
		return nil
	case []byte:
		source := src.([]byte)
		var i WeekDay
		err := json.Unmarshal(source, &i)
		if err != nil {
			return errors.New("WeekDay: can't unmarshal column data")
		}

		*r = i
		return nil
	case int, int8, int32, int64, uint, uint8, uint32, uint64:
		ni := sql.NullInt64{}
		err := ni.Scan(src)
		if err != nil {
			return errors.New("WeekDay: can't scan column data into int64")
		}

		*r = WeekDay(ni.Int64)
		return nil
	}
	return errors.New("WeekDay: invalid type")
}
