base: "base-tmpl" # contains the key name of template name to use for scaffold
specs:
  "base-tmpl": # base template specification
    path: "baseTmpl"
    target:
      path: "base"
    modules:
      "api": # this key is used to target and populate the template part to the base part
        path: "api"
      "db":
        path: "db"
      "simple_worker":
        path: "foobar"
  "foo-tmpl": # additional template spec that serves as an example of how to define new templates in scaffolder
    path: "fooTmpl"
    target:
      path: "base"