build:
	go get github.com/lancer-kit/forge

scaffold-with-gomods:
	./forge new --gomods github.com/out --outdir out

scaffold-with-gopath-git:
	./forge new --gopath github.com/scaffolder/test --gitorigin https://github.com/scaffolder/test.git

scaffold-with-forge-tmpl:
	./forge new  --gomods forga --outdir forga --forgetmpl foobar-tmpl
